config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # get "/" => "quests#index"
  get "/" => "quests#index"

  resources :quests
  resources :banks
  resources :disbursement_dates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank.rb
class Bank < ApplicationRecord
  # Bank.create!(code: "cimb1", bank_type: "cimb", isFpx: true, isObw: false, active: true)
  # Bank.create!(code: "cimb2", bank_type: "cimb", isFpx: false, isObw: true, active: true)
  # Bank.create!(code: "mbb1", bank_type: "maybank", isFpx: false, isObw: true, active: true)
  # Bank.create!(code: "mbb2", bank_type: "maybank", isFpx: false, isObw: true, active: false)
  # Bank.create!(code: "pbb1", bank_type: "public bank", isFpx: true, isObw: false, active: false)

  scope :default_listing, ->(bank_type = nil) {
    query = where(active: true).order(isObw: :desc)
    query = query.where(bank_type: bank_type) if bank_type.present?
    query
  }

  def self.bank_types
    pluck(:bank_type).uniq.compact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  def index
    @banks = Bank.default_listing
    @banks = @banks.where(bank_type: params[:bank_type]) if params[:bank_type].present?
  end
end

app/controllers/disbursement_dates_controller.rb
class DisbursementDatesController < ApplicationController
  def generate_disbursement_date
    disbursement_date = DisbursementDateGeneratorService.new.call(Date.parse(params[:disbursement_date]))
    OpenStruct.new(success: true, disbursement_date: disbursement_date)
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/banks/index.html.erb
<style>
  td, th {
    border: 1px solid #ddd;
    padding: 8px;
  }
</style>

<h1>Bank Listings</h1>

<%= form_with url: banks_path, method: :get, local: true do |f| %>
  <label for="bank_type">Select Bank Type:</label>
  <%= f.select :bank_type, options_for_select(Bank.bank_types.map { |type| [type.humanize, type] }, params[:bank_type]), include_blank: false %>
  <%= f.submit "Filter" %>
<% end %>

<br/>

<table style='border: 1px solid black;'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bank Type</th>
      <th>Active</th>
    </tr>
  </thead>
  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.code %></td>
        <td><%= bank.bank_type %></td>
        <td><%= bank.active ? "Yes" : "No" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Billplz Assignment" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>